name: pages

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    working-directory: docs

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy Github Pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3
      - name: Setup pnpm 🔧
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup node 🔧
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          check-latest: true
          cache: "pnpm"
      - name: Install 🪄
        run: pnpm install --frozen-lockfile
      - name: Build 💎
        run: pnpm run build
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/dist # The folder the action should deploy.
